CREATE TABLE IF NOT EXISTS LPM.PROJECT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  START_DATE DATETIME(6) NOT NULL,
  PLANNED_END_DATE DATETIME(6),
  END_DATE DATETIME(6),
  PRIMARY KEY (ID))
ENGINE = InnoDB;
